### ISSUE TITLE
[Memory] Disable decompression by default, as AsyncDisplayKit manages it.

### ISSUE THREAD

**Issue by appleguy** [ide/WebASDKImageManager#2]
Hey there - thanks for the framework @ide!  It is definitely a need for the community, and you have my Github star :).

There is some discussion of this pitfall here: https://github.com/facebook/AsyncDisplayKit/issues/955

Basically, you really want to make sure that shouldDecompressImages = NO on both the cache and downloader.  This is demonstrated in a code snippet here: https://github.com/rs/SDWebImage/issues/538

This will allow ASDK to use the fetchData range to load the /compressed/ image from disk or network, and then correctly wait until the display range is entered for the decode to start.  Then when -clearContents occurs, the roughly 10x larger decoded version can be evicted from memory while the coded version is still retained in memory, so if it comes back into the display range it can be decoded again immediately.  Lastly, if it keeps scrolling away, -clearFetchedData will be called and then ASDK will relinquish its pointer to even the coded version of the image...relying on any disk cache that is in place, or simply re-fetching from the network if required.

This system works phenomenally well, even in ultra-image-heavy apps like Pinterest and Paper, but it is completely circumvented if the image is decoded when given to ASDK...and will quickly cause apps to crash due to memory pressure.  When working correctly, it is actually far more stable against memory pressure issues than even a traditional SDWebImage or other caching implementation, which has to blindly decide how much memory to spend on the cache rather than proactively deallocating things when they move away from the area of user interest.

Feel free to email me at asyncdisplaykit@gmail.com with any questions / thoughts!

**Comment by ide** [comment]
@appleguy Thanks for reporting this bug with the detail write up. It makes a lot of sense to let the view layer inform which images are actively used.

I'd be interested to learn if people are using WebASDKImageManager alone or if they also use SDWebImage directly in other parts of their app, since that would help decide whether WebASDKImageManager should automatically disable image decompression or not. I'd like to provide good defaults while also offering flexibility.

Some options are:
1. Disable decoding on the default SDWebImageManager's downloader and cache (convenient but concerned it will affect all uses of SDWebImage)
2. Create a new SDWebImageManager for WebASDKImageManager (unobtrusive but we duplicate network requests and storage if the same image is displayed with ASDK and direct use of SDWebImage)
3. Create a new SDWebImageManager with the default SDWebImageManager's downloader with decompression disabled and with a new cache also with decompression disabled (ASDK deduplicates network requests with direct SDWebImage requests but the cache is not shared... this assumes that network requests are more costly than disk & RAM and is an arbitrary policy)
4. Leave the defaults as they are but have WebASDKImageManager print a warning if decompression is left on, with instructions for how to turn the warning off: either disable decompression or set a flag like `webASDKImageManagerInstance.warnsAboutDecompression = @NO`.

I lean towards 4 since it guides people towards the right direction and lets them write the code that's appropriate for their use cases.

Also if someone could help test WebASDKImageManager with SDWebImage decompression disabled, that'd be appreciated.

**Comment by hokster7** [comment]
:+1: I'd really like to see this memory issue resolved. Sorry — I didn't really dig into any of the details because there was too much to read!

What I'll say is that since I've introduced ASDK into my app it now uses both  `SDWebImage` and `PINRemoteImage`... which doesn't really make sense.  I rather have one or the other.

So far it looks like `SDWebImage` loads from the cache faster than `PINRemoteImage` but I cannot be sure whether it was my configuration of ASDK that caused that to appear so.

Would love to see `WebASDKImageManager` as a viable alternative / option when memory issues are resolved.

**Comment by appleguy** [comment]
@fatuhoku could you share any details on the comparison you did? It is actually quite unexpected to me that SDWebImage would be any faster, and it is possible that your measurements may be distorted a bit by the fact that the image library is decoding at the wrong stage.

ASDK now supports a full-featured Image downloader (PINRemoteImage) by simple alloc/init of the ASNetworkImageNode, so particularly because this bug will cause very serious app stability problems for any user of this framework, unfortunately I have to recommend that we share the news within the community that this could deeply affect their production applications.

**Comment by ide** [comment]
I added a notice that ASDK uses PINRemoteImage and PINRemoteCache, recommending it to people who don't have a specific need for SDWebImage.

**Comment by appleguy** [comment]
Thanks!  Just be aware that even for folks with special need for SDWebImage, it’s important to enable decompression, so setting it as the default is the right thing to do.
